eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@10.255.33.108:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: say-hello-service
spring.zipkin.base-url: http://10.255.33.108:9411