eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: zuul-server
zuul:
  routes:
    say-hello-service:
      path: /kepler-calculate/**
      serviceId: kepler-calculate
    greeting-service:
      path: /thread_portfolio/**
      serviceId: thread-portfolio