eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@10.255.33.108:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: zuul-server
  zipkin:
    base-url: http://10.255.33.108:9411
  sleuth:
    sampler:
      percentage: 1.0
zuul:
  routes:
    say-hello-service:
      path: /say-hello-service/**
      serviceId: say-hello-service
    greeting-service:
      path: /greeting-service/**
      serviceId: greeting-service