eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@10.255.33.1085:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: zuul-server
zuul:
  routes:
    kepler-calculate:
      path: /kepler-calculate/**
      serviceId: kepler-calculate
    thread_portfolio:
      path: /thread_portfolio/**
      serviceId: thread-portfolio