eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@10.255.33.108:8761/eureka/
spring:
  application.name: hystrix-terbine-server
server:
  port: 8765
security.basic.enabled: false
turbine:
  aggregator:
    clusterConfig: default   
  appConfig: say-hello-service
  clusterNameExpression: new String("default")