server:
  port: 8761

security:  
  basic:  
    enabled: true  
  user:  
    name: admin  
    password: 123456

eureka:
  instance:
    hostname: 10.255.33.108
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/