eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@10.255.33.108:8761/eureka/
server:
  port: '8767'
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://gitee.com/m148632018/config-server-repo
          username: 657877529@qq.com
          password: mfm9517530
